apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: kspan
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --otlp-addr=otel-collector.default:4317
        image: weaveworks/kspan:main-12eefbe6
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
      serviceAccountName: kspan
      automountServiceAccountToken: true
