apiVersion: v1
kind: Namespace
metadata:
  name: kspan
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kspan
  namespace: kspan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kspan
  namespace: kspan
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kspan
  namespace: kspan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kspan
subjects:
- kind: ServiceAccount
  name: kspan
  namespace: kspan
